baseURL: "https://angelinacho0914.github.io/" 
title: Angelina Cho
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Projects
          url: projects/
          weight: 4
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Books
        #   url: books/
        #   weight: 5 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "I am a student in Master's of Science in Business Analytics (MSBA) at Carnegie Mellon University, Tepper School of Business. I'm skilled in SQL, R, and Python."
    author: Angelina Cho
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Angelina Cho
          subtitle: "I am a student in Master's of Science in Business Analytics (MSBA) at Carnegie Mellon University, Tepper School of Business. I'm skilled in SQL, R, and Python. I am currently in the job market. Feel free to reach out to me at acho2@andrew.cmu.edu"
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Projects
              url: projects/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Resume
          url: resume.pdf
        - name: Email
          url: mailto:acho2@andrew.cmu.edu
        - name: Zoom
          url: https://cmu.zoom.us/j/6790351280
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: LinkedIn
          url: https://www.linkedin.com/in/acho2/
        - name: GitHub
          url: https://github.com/angelinacho0914
        - name: Medium
          url: https://medium.com/@ycho5
        # - name: YouTube
        #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
        # - name: Twitter
        #   url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Angelina Cho"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2